<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gmail</name>
   <tag></tag>
   <elementGuidId>33ab8c0d-d44a-41cf-b1ec-654e39a5b6a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='b_results']/li/h2/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.b_LinksColorMD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>h2 >> internal:has-text=/^Gmail$/ >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>59edd640-89ba-4705-bafa-01deb76eae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://mail.google.com/?login</value>
      <webElementGuid>adb9f01d-ad4b-4f18-b55a-a90014006e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>h</name>
      <type>Main</type>
      <value>ID=SERP,5210.2</value>
      <webElementGuid>bd0ad992-f686-4d31-b0b9-ef2385013d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c2806c2f-8a5c-4917-b17e-970f1a2dcbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b_LinksColorMD</value>
      <webElementGuid>fa8d2202-4fa5-4c55-bf60-b32039521e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gmail</value>
      <webElementGuid>bd7205c5-66f2-49eb-92b2-968cd4ed7969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b_results&quot;)/li[@class=&quot;b_algo b_vtl_deeplinks&quot;]/h2[@class=&quot;b_topTitle&quot;]/a[@class=&quot;b_LinksColorMD&quot;]</value>
      <webElementGuid>df241aa6-68d2-4c91-962f-a5a65f2b1020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='b_results']/li/h2/a</value>
      <webElementGuid>32dbc803-4a0c-40e9-83c1-ea5547e7e7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Gmail')]</value>
      <webElementGuid>4aead1bd-1415-4411-b449-59e4a42ea8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://mail.google.com/?login'])[1]/following::a[1]</value>
      <webElementGuid>1849a854-82d7-445f-9e44-dd5ac810ef99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::a[1]</value>
      <webElementGuid>c283e62a-fa45-42fc-81ca-4555d67b219d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[2]/preceding::a[1]</value>
      <webElementGuid>7f33c8dd-7cab-4bff-9318-5a3d260fc805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::a[2]</value>
      <webElementGuid>7c92b2ad-0bc8-4d70-87f4-4985cc4d31ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://mail.google.com/?login')])[2]</value>
      <webElementGuid>2cf680fa-201b-4413-a268-d06eae54185d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2/a</value>
      <webElementGuid>d5c9ce79-e69a-4bc6-9f2d-553336e574f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://mail.google.com/?login' and (text() = 'Gmail' or . = 'Gmail')]</value>
      <webElementGuid>3d9d9f1a-32f6-4736-a4ad-ce1f5d96984a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
