<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn more_WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</name>
   <tag></tag>
   <elementGuidId>9595ede7-1c19-45b3-b735-36479bec9a2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='next']/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.WpHeLc.VfPpkd-mRLv6.VfPpkd-RLmnJb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Try again&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>086e868c-9fff-4d7d-974b-404caa978484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb</value>
      <webElementGuid>ceff5130-8c65-41f2-a5e0-b0f46f94a5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/restart?continue=https%3A%2F%2Fmyaccount.google.com%3Futm_source%3Daccount-marketing-page%26utm_medium%3Dgo-to-account-button&amp;ddm=0&amp;dsh=S286340852%3A1722522942239517&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AdF4I77MXo-bbk-6aOin_bPrdzFmO0UGlj43yhzXnhL4f2FaELrlCI4_4DlRcFU-mDymmgWPLSOk&amp;service=accountsettings</value>
      <webElementGuid>23f60e32-9272-4e89-936c-8c712e6e66bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Try again</value>
      <webElementGuid>d0762fad-af6f-4901-8fa5-13364cc7c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigation</name>
      <type>Main</type>
      <value>server</value>
      <webElementGuid>36913eb8-0fbe-4c46-9547-53c27db4adc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>hSRGPd</value>
      <webElementGuid>c324b64e-b027-474f-877b-11f03eef1cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next&quot;)/div[@class=&quot;VfPpkd-dgl2Hf-ppHlrf-sM5MNb&quot;]/div[@class=&quot;VfPpkd-LgbsSe VfPpkd-LgbsSe-OWXEXe-k8QpJ VfPpkd-LgbsSe-OWXEXe-dgl2Hf nCP5yc AjY5Oe DuMIQc LQeN7 BqKGqe Jskylb TrZEUc lw1w4b VfPpkd-ksKsZd-mWPk3d-OWXEXe-Tv8l5d-lJfZMc VfPpkd-ksKsZd-mWPk3d&quot;]/a[@class=&quot;WpHeLc VfPpkd-mRLv6 VfPpkd-RLmnJb&quot;]</value>
      <webElementGuid>eda0d9c1-77d7-49fa-8a92-907104a49f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='next']/div/div/a</value>
      <webElementGuid>6c003f79-c4b1-4d9f-8847-7f589b305913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/restart?continue=https%3A%2F%2Fmyaccount.google.com%3Futm_source%3Daccount-marketing-page%26utm_medium%3Dgo-to-account-button&amp;ddm=0&amp;dsh=S286340852%3A1722522942239517&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AdF4I77MXo-bbk-6aOin_bPrdzFmO0UGlj43yhzXnhL4f2FaELrlCI4_4DlRcFU-mDymmgWPLSOk&amp;service=accountsettings')]</value>
      <webElementGuid>38f4c82f-de39-49fd-8e04-981f8ed8e0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>bb97e760-db45-4348-be04-74ceb1000bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/restart?continue=https%3A%2F%2Fmyaccount.google.com%3Futm_source%3Daccount-marketing-page%26utm_medium%3Dgo-to-account-button&amp;ddm=0&amp;dsh=S286340852%3A1722522942239517&amp;flowEntry=ServiceLogin&amp;flowName=GlifWebSignIn&amp;ifkv=AdF4I77MXo-bbk-6aOin_bPrdzFmO0UGlj43yhzXnhL4f2FaELrlCI4_4DlRcFU-mDymmgWPLSOk&amp;service=accountsettings']</value>
      <webElementGuid>9af2f0df-8c08-49e9-8c06-c328091f611c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
