<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Invalid User Name or PassWord_enterbtn</name>
   <tag></tag>
   <elementGuidId>ce92b27b-287f-4027-979c-f3e2f4b8eec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enterbtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='enterbtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logo missing&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>80f20a06-0147-4f15-84db-ce5e67c2e41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>enter2.png</value>
      <webElementGuid>ad60d386-c937-4f56-b1b2-23ad84ac633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo missing</value>
      <webElementGuid>e0efe642-f74f-4b70-a0d2-a6f55e8d15cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enterbtn</value>
      <webElementGuid>f383f137-3f42-43c2-aa9f-fd0ef55f4776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>CheckCredentials()</value>
      <webElementGuid>2b8bd57d-6ff1-4102-b885-e53aaccc4085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enterbtn&quot;)</value>
      <webElementGuid>12daf4df-b52c-4aef-8ceb-73c5443bc536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='enterbtn']</value>
      <webElementGuid>6da9c254-17a1-4ac0-8d34-b0dff4fbaaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo missing']</value>
      <webElementGuid>3d6c676e-ce9d-4429-8206-755782b9bf91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>c2c33b7c-7365-4a3a-a35e-1f5f48263e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'enter2.png' and @alt = 'Logo missing' and @id = 'enterbtn']</value>
      <webElementGuid>25567f5d-8035-499d-9650-bb6abcec6552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
